### ISSUE TITLE
problem with account section

### ISSUE THREAD

**Issue by mfiano** [sb-/OpenExchange#4]
i am just trying this out for the first time. we want to use it to trade between 2 altcoins (no btc or ltc daemon). i added the required info to config.py for our 2 altcoin daemons. seems to work fine until i click on the account section:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/axion/OpenExchange/app.py", line 58, in account
    return account_page()
  File "/home/axion/OpenExchange/app.py", line 391, in account_page
    return render_template('account.html', currencies=config.get_currencies(),openorders=openorders(session['userid']),**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/axion/OpenExchange/templates/account.html", line 134, in top-level template code
    <li class="list-group-item">{{ currencies[currency]['name'] }} - {{getbalance(currency,session['userid'])}} {{ currency.upper() }}
  File "/home/axion/OpenExchange/app.py", line 259, in getbalance
    return check_balance(c, uid)/config.get_multiplier(c)
  File "/home/axion/OpenExchange/app.py", line 251, in check_balance
    return baldict[currency]
KeyError: 'max'

**Comment by sb-** [comment]
Check issue 3 - some parts of the exchange have not been updated to reflect the changes to the new, easier configuration. To add a currency, add the table in SQL (max_balance i assume would be the right table for this coin) and change adjustbalance/checkbalance to work with these coins

**Comment by mfiano** [comment]
thanks. are you on freenode? i am interested in forking this project/working together.

**Comment by sb-** [comment]
Sure, what's your name on there?

**Comment by mfiano** [comment]
axion
